# ──────────────────────────────────────────────────
# Additional Analysis
# Part of: Belief Updating with Misinformation analysis pipeline
#
# Items 1–11 from revision task list:
#  Group A (1–3):  Mean bias (over_report) by prior block for regular,
#                  retractions, confirmations — tables + TikZ figures
#  Group B (4):    Opposite-signal bias by prior block
#  Group C (5):    Frequency table: rounds × prior bins (Exp 1)
#  Group D (6–8):  c and d by individual round for each signal type
#  Group E (9–11): c and d by prior block for each signal type
#  Group F (12–14): c and d by temporal period block (Early/Middle/Late)
#
# Outputs: output/additional/tables/*.tex
#          output/additional/figures/*.jpg  (ggplot)
#          output/additional/figures/*.tex  (TikZ snippets for \input{})
# ──────────────────────────────────────────────────


######################################################
# SETUP (auto-loads if run standalone)
######################################################
if (!exists(".utils_loaded")) {
  inpath      <- "data/processed"
  output_type <- "latex"
  set_dpi     <- 400
  source("code/utils/packages.R")
  source("code/utils/constants.R")
  source("code/utils/helpers.R")
  source("code/utils/plot_theme.R")
  source("code/utils/run_control.R")
  .utils_loaded <- TRUE
  source("code/utils/derived_variables.R")
}

dir.create("output/additional/tables",  recursive = TRUE, showWarnings = FALSE)
dir.create("output/additional/figures", recursive = TRUE, showWarnings = FALSE)

add_fig  <- function(name) paste0("output/additional/figures/", name, ".jpg")
add_tikz <- function(name) paste0("output/additional/figures/", name, ".tex")
add_tab  <- function(name) paste0("output/additional/tables/",  name, ".tex")


######################################################
# SHARED: prior_aligned_bin for df_regular
# (df_retract has prior_aligned_bin and df_confirm has
#  belief_lag2_bin already from derived_variables.R)
######################################################
df_regular$prior_aligned <- ifelse(
  df_regular$ball_red == 1,
  df_regular$belief_lag1,
  1 - df_regular$belief_lag1
)
df_regular$prior_aligned_bin <- factor(
  cut(df_regular$prior_aligned,
      breaks = prior_bin_breaks, include.lowest = TRUE,
      labels = prior_bin_labels),
  levels = prior_bin_labels
)


######################################################
# HELPER: LaTeX table — mean, SD, N by bin
######################################################
write_mean_sd_tex <- function(tbl, out_path, caption, label,
                               col_label = "Mean Bias") {
  # tbl must have columns: prior_bin, Mean, SD, N
  tbl <- tbl[order(factor(tbl$prior_bin, levels = prior_bin_labels)), ]

  lines <- c(
    "\\begin{table}[htbp]",
    "\\centering",
    paste0("\\caption{", caption, "}"),
    paste0("\\label{", label, "}"),
    "\\begin{tabular}{lrrr}",
    "\\hline",
    paste0("Prior Bin & ", col_label, " & SD & $N$ \\\\"),
    "\\hline"
  )
  for (i in seq_len(nrow(tbl))) {
    lines <- c(lines,
      sprintf("%s\\%% & %.4f & %.4f & %d \\\\",
              as.character(tbl$prior_bin[i]),
              tbl$Mean[i], tbl$SD[i], tbl$N[i])
    )
  }
  lines <- c(lines, "\\hline",
    paste0("\\multicolumn{4}{l}{\\small SD is descriptive (raw distribution).",
           " $N$ = observations per bin.} \\\\"),
    "\\end{tabular}", "\\end{table}"
  )
  writeLines(lines, out_path)
  invisible(tbl)
}


######################################################
# HELPER: TikZ bias-bar figure (for mean bias plots)
#
# tbl: data.frame with columns prior_bin, Mean, SD (10 rows)
# overreact_label_side: "above" if positive = overreact,
#                        "below" if positive = underreact (like retraction TikZ)
######################################################
write_tikz_bias <- function(tbl, out_path, ylabel,
                             positive_label = "Overreacts") {
  tbl <- tbl[order(factor(tbl$prior_bin, levels = prior_bin_labels)), ]
  bin_mids <- seq(0.05, 0.95, 0.1)

  # y-axis range: cover mean ± SD, always include zero
  y_lo <- min(c(0, tbl$Mean - tbl$SD), na.rm = TRUE)
  y_hi <- max(c(0, tbl$Mean + tbl$SD), na.rm = TRUE)
  pad  <- max(abs(c(y_lo, y_hi))) * 0.2
  y_lo <- floor((y_lo - pad) * 10) / 10
  y_hi <- ceiling((y_hi + pad) * 10) / 10

  neg_label <- if (positive_label == "Overreacts") "Underreacts" else "Overreacts"

  # Position for Overreacts/Underreacts labels (60% of positive/negative range)
  pos_mid <- y_hi * 0.6
  neg_mid <- y_lo * 0.6

  lines <- c(
    paste0("% Auto-generated by 04_additional_analysis.R — do not edit"),
    paste0("% y > 0: ", positive_label, "  |  y < 0: ", neg_label),
    "\\begin{tikzpicture}[scale=12]",
    sprintf("\\draw[help lines,step=0.1] (0,%.1f) grid (1,%.1f);", y_lo, y_hi)
  )

  for (i in 1:10) {
    m <- tbl$Mean[i]
    s <- tbl$SD[i]
    if (is.na(m) || is.na(s)) next
    x <- bin_mids[i]
    lines <- c(lines,
      sprintf("\\filldraw[opaque,white!80!black] (%.2f,0) rectangle (%.2f,%.4f);",
              x - 0.02, x + 0.02, m),
      sprintf("\\draw[line width=0.6] (%.2f,0) rectangle (%.2f,%.4f);",
              x - 0.02, x + 0.02, m),
      sprintf("\\draw[line width=0.6,|-|] (%.2f,%.4f) -- (%.2f,%.4f);",
              x, m - s, x, m + s)
    )
  }

  lines <- c(lines,
    sprintf("\\draw[line width=0.8,->]  (0,0) -- (1.1,0) node[below] {\\small{$p_{t-1}(R)$}};"),
    sprintf("\\draw[line width=0.8,<->] (0,%.1f) -- (0,%.1f) node[above] {%s};",
            y_lo, y_hi, ylabel),
    sprintf("\\draw (0,%.2f) node[above,rotate=90] {\\small{%s}};",
            pos_mid, positive_label),
    sprintf("\\draw (0,%.2f) node[above,rotate=90] {\\small{%s}};",
            neg_mid, neg_label),
    "% ADD THEORY CURVE BELOW IF NEEDED:",
    "% \\draw[red,line width=1.2,domain=0.01:0.99] plot(\\x,{...});",
    "\\end{tikzpicture}"
  )
  writeLines(lines, out_path)
  invisible(tbl)
}


######################################################
# GROUP A: ITEMS 1–3 — MEAN BIAS BY PRIOR BIN
######################################################
cat(">> Group A: mean bias by prior bin...\n")

# Item 1 — Regular signals
# Exclude round 1 (no prior history) and round 12 (last positional slot)
# over_report > 0: over-reacts (too much weight on signal)
reg_bias <- df_regular %>%
  filter(round > 1, round < 12) %>%
  group_by(prior_bin = prior_aligned_bin) %>%
  summarise(Mean = mean(over_report, na.rm = TRUE),
            SD   = sd(over_report,   na.rm = TRUE),
            N    = n(), .groups = "drop")

write_mean_sd_tex(reg_bias, add_tab("tab_reg_bias_by_prior"),
  "Mean Bias by Prior Block: Regular Signals",
  "tab:reg_bias_prior", "Mean Over-Report")

write_tikz_bias(reg_bias, add_tikz("fig_reg_bias_by_prior"),
  ylabel        = "\\small{Over-report}",
  positive_label = "Overreacts")

# Item 2 — Retractions
# over_report_ret > 0: under-reacts (belief still biased toward initial signal)
ret_bias <- df_retract %>%
  group_by(prior_bin = prior_aligned_bin) %>%
  summarise(Mean = mean(over_report_ret, na.rm = TRUE),
            SD   = sd(over_report_ret,   na.rm = TRUE),
            N    = n(), .groups = "drop")

write_mean_sd_tex(ret_bias, add_tab("tab_ret_bias_by_prior"),
  "Mean Bias by Prior Block: Retractions",
  "tab:ret_bias_prior", "Mean Bias (biased toward initial signal)")

write_tikz_bias(ret_bias, add_tikz("fig_ret_bias_by_prior"),
  ylabel        = "\\small{$b_{t+1}(R|r,\\xmark)$}",
  positive_label = "Underreacts")  # matches user's TikZ: positive = underreact

# Item 3 — Confirmations
# over_report > 0: over-reacts to confirmation
conf_bias <- df_confirm %>%
  group_by(prior_bin = belief_lag2_bin) %>%
  summarise(Mean = mean(over_report, na.rm = TRUE),
            SD   = sd(over_report,   na.rm = TRUE),
            N    = n(), .groups = "drop")

write_mean_sd_tex(conf_bias, add_tab("tab_conf_bias_by_prior"),
  "Mean Bias by Prior Block: Confirmations",
  "tab:conf_bias_prior", "Mean Over-Report")

write_tikz_bias(conf_bias, add_tikz("fig_conf_bias_by_prior"),
  ylabel        = "\\small{Over-report}",
  positive_label = "Overreacts")

cat("   Items 1–3 done\n")


######################################################
# GROUP B: ITEM 4 — OPPOSITE-SIGNAL BIAS BY PRIOR BIN
######################################################
cat(">> Group B: opposite-signal bias by prior bin...\n")

# Opposite signals: second ball is opposite color to first
# prev_ball = color of first ball (from 00_prepare_data.R)
df_main_ver <- df_main[!is.na(df_main$two_balls), ]
df_opp      <- df_main_ver[df_main_ver$two_balls %in% c("BR", "RB"), ]

# Prior aligned with the FIRST signal direction, BEFORE the first signal (belief_lag2)
# Parallel to retraction analysis: how strong was prior before the initial signal?
df_opp$prior_aligned_opp <- ifelse(
  df_opp$prev_ball == 1,
  df_opp$belief_lag2,
  1 - df_opp$belief_lag2
)
df_opp$prior_bin_opp <- factor(
  cut(df_opp$prior_aligned_opp,
      breaks = prior_bin_breaks, include.lowest = TRUE,
      labels = prior_bin_labels),
  levels = prior_bin_labels
)

# -over_report2 > 0: belief still biased toward initial signal (parallel to retractions)
df_opp$bias_opp <- -df_opp$over_report2

opp_bias <- df_opp %>%
  group_by(prior_bin = prior_bin_opp) %>%
  summarise(Mean = mean(bias_opp, na.rm = TRUE),
            SD   = sd(bias_opp,   na.rm = TRUE),
            N    = n(), .groups = "drop")

write_mean_sd_tex(opp_bias, add_tab("tab_opp_bias_by_prior"),
  "Mean Bias by Prior Block: Opposite Signals",
  "tab:opp_bias_prior", "Mean Bias (biased toward initial signal)")

write_tikz_bias(opp_bias, add_tikz("fig_opp_bias_by_prior"),
  ylabel        = "\\small{$b_{t+1}(R|r,\\text{opp})$}",
  positive_label = "Underreacts")

cat("   Item 4 done\n")


######################################################
# GROUP C: ITEM 5 — FREQUENCY TABLE (ROUNDS × PRIOR BINS)
######################################################
cat(">> Group C: frequency table (rounds x prior bins)...\n")

# Experiment 1, regular signals, rounds 2–11
# (round 1: no prior updating history; round 12: last positional slot)
freq_raw <- df_regular %>%
  filter(treat_aggregate_signal == 0, round >= 2, round <= 11) %>%
  count(round, prior_bin = prior_aligned_bin) %>%
  tidyr::pivot_wider(
    names_from  = prior_bin,
    values_from = n,
    values_fill = 0L
  ) %>%
  arrange(round)

# Ensure all 10 prior bin columns present in order
for (col in prior_bin_labels) {
  if (!col %in% names(freq_raw)) freq_raw[[col]] <- 0L
}
freq_tbl <- freq_raw[, c("round", prior_bin_labels)]

n_bins <- length(prior_bin_labels)
lines <- c(
  "\\begin{table}[htbp]",
  "\\centering",
  paste0("\\caption{Number of Observations by Round and Prior Belief Block ",
         "(Regular Signals, Experiment 1, Rounds 2--11)}"),
  "\\label{tab:freq_round_prior}",
  paste0("\\resizebox{\\textwidth}{!}{\\begin{tabular}{l",
         paste(rep("r", n_bins), collapse = ""), "}}"),
  "\\hline",
  paste0("Round & ",
         paste(paste0(prior_bin_labels, "\\%"), collapse = " & "),
         " \\\\"),
  "\\hline"
)
for (i in seq_len(nrow(freq_tbl))) {
  row_vals <- c(as.character(freq_tbl$round[i]),
                as.character(unlist(freq_tbl[i, prior_bin_labels])))
  lines <- c(lines, paste(row_vals, collapse = " & "), " \\\\")
}
lines <- c(lines,
  "\\hline",
  "\\multicolumn{11}{l}{\\small Each cell = number of regular-signal observations",
  "  at that (round, prior bin) combination.} \\\\",
  "\\end{tabular}}",
  "\\end{table}"
)
writeLines(lines, add_tab("tab_freq_round_prior"))

cat("   Item 5 done\n")


######################################################
# HELPER: c and d by subgroup (separate OLS per cell)
#
# signal_var: "signal_ratio"     for regular signals
#             "signal_ratio_obj" for retractions/confirmations
#   For regular signals, signal_ratio = signal_ratio_obj = ±log(0.6/0.4):
#   both recover the same objective value since posterior_subj is computed
#   from the true urn probabilities, so added_info() just inverts back to 0.6/0.4.
#   For retractions/confirmations, signal_ratio_obj is used because the
#   objective signal magnitude is fixed by design (±log(0.6/0.4) and ±log(2)).
######################################################
run_cd_by <- function(df, group_var, signal_var = "signal_ratio") {
  formula_str <- paste0("obs_log_post_ratio ~ ", signal_var, " + prior_ratio")
  groups <- sort(unique(df[[group_var]]))
  results <- lapply(groups, function(g) {
    sub <- df[!is.na(df[[group_var]]) & df[[group_var]] == g, ]
    if (nrow(sub) < 10) return(NULL)  # skip underpowered cells
    # Need variation in signal_var — skip if constant within cell
    if (length(unique(sub[[signal_var]])) < 2) return(NULL)
    fit <- tryCatch(
      lm(as.formula(formula_str), data = sub),
      error = function(e) NULL
    )
    if (is.null(fit)) return(NULL)
    beta <- coef(fit)
    se   <- sqrt(diag(vcov(fit)))
    data.frame(
      group     = g,
      param     = c("c", "d"),
      estimate  = c(beta["prior_ratio"],   beta[[signal_var]]),
      std.error = c(se["prior_ratio"],      se[[signal_var]]),
      n         = nrow(sub),
      stringsAsFactors = FALSE
    )
  })
  out <- do.call(rbind, results)
  names(out)[names(out) == "group"] <- group_var
  out
}


######################################################
# HELPER: Two-panel LaTeX c/d table
#   Panel A: c (base-rate use) by signal type
#   Panel B: d (inference)     by signal type
#   Rows = round or prior bin;  Cols = Regular | Retraction | Confirmation
#   SE on separate row in parentheses (standard economics format)
######################################################
write_cd_tex <- function(cd_long, group_var, bins_ordered,
                          out_path, caption, label,
                          note = NULL) {
  get_cell <- function(g, param, sig) {
    row <- cd_long[cd_long[[group_var]] == g &
                     cd_long$param == param &
                     cd_long$signal_type == sig, ]
    if (nrow(row) == 0 || is.na(row$estimate[1]))
      return(list(est = "---", se = ""))
    list(est = sprintf("%.3f", row$estimate[1]),
         se  = sprintf("(%.3f)", row$std.error[1]))
  }

  grp_label <- tools::toTitleCase(gsub("_", " ", group_var))
  sig_types <- c("Regular", "Retraction", "Confirmation")

  header <- paste0(grp_label, " & Regular & Retraction & Confirmation \\\\")

  make_panel <- function(param_name, panel_label) {
    lines <- c(
      sprintf("\\multicolumn{4}{l}{\\textit{Panel %s: %s}} \\\\", panel_label,
              if (param_name == "c") "Base-Rate Use ($c$)" else "Inference ($d$)"),
      "\\hline",
      header,
      "\\hline"
    )
    for (g in bins_ordered) {
      cells <- lapply(sig_types, function(s) get_cell(g, param_name, s))
      # estimate row
      lines <- c(lines,
        paste(c(as.character(g), sapply(cells, `[[`, "est")), collapse = " & "),
        " \\\\"
      )
      # SE row (blank first column)
      se_vals <- sapply(cells, `[[`, "se")
      if (any(nzchar(se_vals))) {
        lines <- c(lines,
          paste(c("", se_vals), collapse = " & "),
          " \\\\"
        )
      }
    }
    lines <- c(lines, "\\hline")
    lines
  }

  default_note <- paste0(
    "SEs in parentheses. Separate OLS per cell. ",
    "Cells with $n<10$ or no signal variation omitted (---). ",
    "Bayesian benchmark: $c=d=1$. ",
    "Signal variable: $\\pm$log(0.6/0.4) for regular signals and retractions; ",
    "$\\pm$log(2) for confirmations."
  )

  lines <- c(
    "\\begin{table}[htbp]",
    "\\centering",
    paste0("\\caption{", caption, "}"),
    paste0("\\label{", label, "}"),
    "\\begin{tabular}{lrrr}",
    "\\hline",
    make_panel("c", "A"),
    "",
    make_panel("d", "B"),
    "",
    paste0("\\multicolumn{4}{p{0.85\\textwidth}}{\\small ",
           if (!is.null(note)) note else default_note, "} \\\\"),
    "\\end{tabular}",
    "\\end{table}"
  )
  writeLines(lines, out_path)
  invisible(lines)
}


######################################################
# HELPER: Markdown overview writer (for VS Code preview)
# Appends a formatted section to the overview .md file
######################################################
md_path <- "output/additional/overview.md"

md_init <- function() {
  writeLines(c(
    "# Additional Analysis — Overview",
    paste0("_Generated: ", Sys.time(), "_"),
    "",
    "Open this file in VS Code and press **Ctrl+Shift+V** to preview.",
    ""
  ), md_path)
}

md_append_bias <- function(tbl, title) {
  tbl <- tbl[order(factor(tbl$prior_bin, levels = prior_bin_labels)), ]
  header <- "| Prior Bin | Mean | SD | N |"
  sep    <- "|-----------|-----:|---:|--:|"
  rows   <- sprintf("| %s | %.4f | %.4f | %d |",
                    tbl$prior_bin, tbl$Mean, tbl$SD, tbl$N)
  lines  <- c(paste0("## ", title), "", header, sep, rows, "")
  cat(lines, sep = "\n", append = TRUE, file = md_path)
}

md_append_cd <- function(cd_long, group_var, bins_ordered, title) {
  sig_types <- c("Regular", "Retraction", "Confirmation")

  for (param_name in c("c", "d")) {
    param_title <- if (param_name == "c") "Base-Rate Use (c)" else "Inference (d)"
    header <- paste0("| ", tools::toTitleCase(gsub("_"," ",group_var)),
                     " | Regular | Retraction | Confirmation |")
    sep    <- paste0("|", paste(rep("---|", 4), collapse=""))

    rows <- vapply(bins_ordered, function(g) {
      get_val <- function(sig) {
        row <- cd_long[cd_long[[group_var]] == g &
                         cd_long$param == param_name &
                         cd_long$signal_type == sig, ]
        if (nrow(row) == 0 || is.na(row$estimate[1]))
          return("---")
        sprintf("%.3f (%.3f)", row$estimate[1], row$std.error[1])
      }
      paste0("| ", g, " | ", get_val("Regular"), " | ",
             get_val("Retraction"), " | ", get_val("Confirmation"), " |")
    }, character(1))

    lines <- c(paste0("### ", title, " — ", param_title),
               "", header, sep, rows, "")
    cat(lines, sep = "\n", append = TRUE, file = md_path)
  }
}



######################################################
# GROUP D: ITEMS 6–8 — c AND d BY ROUND
# All signal types use the objective log-likelihood ratio:
#   Regular:       signal_ratio     = ±log(0.6/0.4) (equals signal_ratio_obj for regular rounds)
#   Retractions:   signal_ratio_obj = ±log(0.6/0.4) (sign reversed vs original signal)
#   Confirmations: signal_ratio_obj = ±log(2)
# Variation within a cell comes from sign (ball direction), not magnitude.
######################################################
cat(">> Group D: c and d by round...\n")

cd_reg_round  <- run_cd_by(df_regular, "round", signal_var = "signal_ratio")
cd_ret_round  <- run_cd_by(df_retract, "round", signal_var = "signal_ratio_obj")
cd_conf_round <- run_cd_by(df_confirm,  "round", signal_var = "signal_ratio_obj")

cd_reg_round$signal_type  <- "Regular"
cd_ret_round$signal_type  <- "Retraction"
cd_conf_round$signal_type <- "Confirmation"

cd_by_round <- rbind(cd_reg_round, cd_ret_round, cd_conf_round)

# LaTeX table (two-panel: Panel A = c, Panel B = d)
all_rounds <- sort(unique(cd_by_round$round))
write_cd_tex(cd_by_round, "round", all_rounds,
  add_tab("tab_cd_by_round"),
  "$c$ and $d$ Estimates by Round",
  "tab:cd_by_round")

# ggplot coefficient plot
cd_by_round$param_label <- ifelse(cd_by_round$param == "c",
                                   "Base-Rate Use (c)", "Inference (d)")

fig_cd_round <- ggplot(cd_by_round,
    aes(x = round, y = estimate,
        color = signal_type, group = signal_type)) +
  geom_point(size = 1.5) +
  geom_line() +
  geom_errorbar(aes(ymin = estimate - 1.96 * std.error,
                    ymax = estimate + 1.96 * std.error), width = 0.3) +
  geom_hline(yintercept = 1, linetype = "dashed", color = "grey50") +
  facet_wrap(~ param_label, ncol = 2) +
  scale_x_continuous(breaks = 1:12, name = "Round") +
  scale_color_brewer(palette = "Set1", name = NULL) +
  ylab("Estimate  (1 = Bayesian)") +
  theme_classic() +
  theme(legend.position = "bottom")

ggsave(add_fig("fig_cd_by_round"),
       fig_cd_round, width = 10, height = 5, units = "in", dpi = set_dpi)

cat("   Items 6–8 done\n")


######################################################
# GROUP E: ITEMS 9–11 — c AND d BY PRIOR BIN
# Same signal variable choice as Group D
######################################################
cat(">> Group E: c and d by prior bin...\n")

# Standardise the prior_bin column to "prior_bin_e" for each dataset
# Exclude round 1 (no prior history) and round 12 (last positional slot)
df_regular$prior_bin_e  <- df_regular$prior_aligned_bin
df_retract$prior_bin_e  <- df_retract$prior_aligned_bin
df_confirm$prior_bin_e  <- df_confirm$belief_lag2_bin

cd_reg_prior  <- run_cd_by(df_regular[df_regular$round > 1 & df_regular$round < 12, ],
                            "prior_bin_e", signal_var = "signal_ratio")
cd_ret_prior  <- run_cd_by(df_retract[df_retract$round > 1 & df_retract$round < 12, ],
                            "prior_bin_e", signal_var = "signal_ratio_obj")
cd_conf_prior <- run_cd_by(df_confirm[df_confirm$round > 1 & df_confirm$round < 12, ],
                            "prior_bin_e", signal_var = "signal_ratio_obj")

# Rename group column
rename_grp <- function(df) {
  names(df)[names(df) == "prior_bin_e"] <- "prior_bin"
  df
}
cd_reg_prior  <- rename_grp(cd_reg_prior)
cd_ret_prior  <- rename_grp(cd_ret_prior)
cd_conf_prior <- rename_grp(cd_conf_prior)

cd_reg_prior$signal_type  <- "Regular"
cd_ret_prior$signal_type  <- "Retraction"
cd_conf_prior$signal_type <- "Confirmation"

cd_by_prior <- rbind(cd_reg_prior, cd_ret_prior, cd_conf_prior)
cd_by_prior$prior_bin <- factor(cd_by_prior$prior_bin, levels = prior_bin_labels)

# LaTeX table (two-panel: Panel A = c, Panel B = d)
write_cd_tex(cd_by_prior, "prior_bin", prior_bin_labels,
  add_tab("tab_cd_by_prior"),
  "$c$ and $d$ Estimates by Prior Block",
  "tab:cd_by_prior")

# ggplot coefficient plot: all signal types overlaid
cd_by_prior$param_label <- ifelse(cd_by_prior$param == "c",
                                   "Base-Rate Use (c)", "Inference (d)")

fig_cd_prior <- ggplot(cd_by_prior,
    aes(x = prior_bin, y = estimate,
        color = signal_type, group = signal_type)) +
  geom_point(size = 1.5) +
  geom_line() +
  geom_errorbar(aes(ymin = estimate - 1.96 * std.error,
                    ymax = estimate + 1.96 * std.error), width = 0.3) +
  geom_hline(yintercept = 1, linetype = "dashed", color = "grey50") +
  facet_wrap(~ param_label, ncol = 2) +
  scale_color_brewer(palette = "Set1", name = NULL) +
  xlab("Prior bin (aligned with signal)") +
  ylab("Estimate  (1 = Bayesian)") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "bottom")

ggsave(add_fig("fig_cd_by_prior"),
       fig_cd_prior, width = 10, height = 5, units = "in", dpi = set_dpi)

cat("   Items 9–11 done\n")


######################################################
# GROUP F: c AND d BY TEMPORAL PERIOD BLOCK
# Regular:              Early=2-4, Middle=5-7, Late=8-10
# Retractions/Confirms: Early=3-5, Middle=6-8, Late=9-11
######################################################
cat(">> Group F: c and d by period block...\n")

assign_period_block_reg <- function(r) {
  ifelse(r %in% 2:4,  "Early",
  ifelse(r %in% 5:7,  "Middle",
  ifelse(r %in% 8:10, "Late", NA_character_)))
}
assign_period_block_retconf <- function(r) {
  ifelse(r %in% 3:5,  "Early",
  ifelse(r %in% 6:8,  "Middle",
  ifelse(r %in% 9:11, "Late", NA_character_)))
}

df_reg_pb  <- df_regular
df_ret_pb  <- df_retract
df_conf_pb <- df_confirm

df_reg_pb$period_block  <- assign_period_block_reg(df_reg_pb$round)
df_ret_pb$period_block  <- assign_period_block_retconf(df_ret_pb$round)
df_conf_pb$period_block <- assign_period_block_retconf(df_conf_pb$round)

df_reg_pb  <- df_reg_pb[!is.na(df_reg_pb$period_block), ]
df_ret_pb  <- df_ret_pb[!is.na(df_ret_pb$period_block), ]
df_conf_pb <- df_conf_pb[!is.na(df_conf_pb$period_block), ]

block_order <- c("Early", "Middle", "Late")
df_reg_pb$period_block  <- factor(df_reg_pb$period_block,  levels = block_order)
df_ret_pb$period_block  <- factor(df_ret_pb$period_block,  levels = block_order)
df_conf_pb$period_block <- factor(df_conf_pb$period_block, levels = block_order)

cd_reg_pb  <- run_cd_by(df_reg_pb,  "period_block", signal_var = "signal_ratio")
cd_ret_pb  <- run_cd_by(df_ret_pb,  "period_block", signal_var = "signal_ratio_obj")
cd_conf_pb <- run_cd_by(df_conf_pb, "period_block", signal_var = "signal_ratio_obj")

cd_reg_pb$signal_type  <- "Regular"
cd_ret_pb$signal_type  <- "Retraction"
cd_conf_pb$signal_type <- "Confirmation"

cd_by_period <- rbind(cd_reg_pb, cd_ret_pb, cd_conf_pb)
cd_by_period$period_block <- factor(cd_by_period$period_block, levels = block_order)

period_note <- paste0(
  "SEs in parentheses. One OLS regression per signal type $\\times$ period block (9 regressions total). ",
  "Bayesian benchmark: $c=d=1$. ",
  "Round windows: Regular = Early (2--4), Middle (5--7), Late (8--10); ",
  "Retractions/Confirmations = Early (3--5), Middle (6--8), Late (9--11). ",
  "Signal variable: $\\pm$log(0.6/0.4) for regular signals and retractions; ",
  "$\\pm$log(2) for confirmations."
)
write_cd_tex(cd_by_period, "period_block", block_order,
  add_tab("tab_cd_by_period"),
  "$c$ and $d$ Estimates by Period Block",
  "tab:cd_by_period",
  note = period_note)

cd_by_period$param_label <- ifelse(cd_by_period$param == "c",
                                    "Base-Rate Use (c)", "Inference (d)")

fig_cd_period <- ggplot(cd_by_period,
    aes(x = period_block, y = estimate,
        color = signal_type, group = signal_type)) +
  geom_point(size = 2, position = position_dodge(0.3)) +
  geom_line(position = position_dodge(0.3)) +
  geom_errorbar(aes(ymin = estimate - 1.96 * std.error,
                    ymax = estimate + 1.96 * std.error),
                width = 0.2, position = position_dodge(0.3)) +
  geom_hline(yintercept = 1, linetype = "dashed", color = "grey50") +
  facet_wrap(~ param_label, ncol = 2) +
  scale_color_brewer(palette = "Set1", name = NULL) +
  xlab("Period Block") +
  ylab("Estimate  (1 = Bayesian)") +
  theme_classic() +
  theme(legend.position = "bottom")

ggsave(add_fig("fig_cd_by_period"),
       fig_cd_period, width = 10, height = 5, units = "in", dpi = set_dpi)

cat("   Group F done\n")


######################################################
# MARKDOWN OVERVIEW (for VS Code preview: Ctrl+Shift+V)
######################################################
cat(">> Writing markdown overview...\n")

md_init()

# Bias tables
md_append_bias(reg_bias,  "Item 1 — Mean Bias by Prior: Regular Signals (over_report > 0 = overreacts)")
md_append_bias(ret_bias,  "Item 2 — Mean Bias by Prior: Retractions (over_report_ret > 0 = underreacts)")
md_append_bias(conf_bias, "Item 3 — Mean Bias by Prior: Confirmations (over_report > 0 = overreacts)")
md_append_bias(opp_bias,  "Item 4 — Mean Bias by Prior: Opposite Signals (-over_report2 > 0 = biased toward initial)")

# c/d by round
cat("## Items 6–8 — c and d by Round\n\n", file = md_path, append = TRUE)
cat(paste0("_Signal variable: ±log(0.6/0.4) for regular signals and retractions; ",
           "±log(2) for confirmations._\n\n"),
    file = md_path, append = TRUE)
md_append_cd(cd_by_round, "round", all_rounds, "c and d by Round")

# c/d by prior
cat("## Items 9–11 — c and d by Prior Block\n\n", file = md_path, append = TRUE)
md_append_cd(cd_by_prior, "prior_bin", prior_bin_labels, "c and d by Prior Block")

# c/d by period block
cat("## Group F — c and d by Period Block\n\n", file = md_path, append = TRUE)
cat(paste0("_Regular: Early=2-4, Middle=5-7, Late=8-10. ",
           "Retractions/Confirmations: Early=3-5, Middle=6-8, Late=9-11._\n\n"),
    file = md_path, append = TRUE)
md_append_cd(cd_by_period, "period_block", block_order, "c and d by Period Block")

cat("   Markdown written to output/additional/overview.md\n")
cat("   Open in VS Code and press Ctrl+Shift+V to preview\n")
cat(">> 04_additional_analysis.R complete\n")
